src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;


#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    
    #[Assert\Length(
        max: 255,
        maxMessage: 'Le nom ne doit pas depasser {{ limit }} caractères',
    )]
    #[Assert\NotBlank(message: 'Le nom est obligatoire')]
    #[ORM\Column(length: 255)]
    private ?string $name = null;
    
    #[Gedmo\Slug(fields: ['name'])]
    #[ORM\Column(length: 255)]
    private ?string $slug = null;


    #[Assert\File(
        maxSize: '4000k',
        extensions: ['jpeg', 'png', 'jpg', 'webp'],
        extensionsMessage: 'Veuillez selectionner une image dont le format est "png, jpg, jpeg ou webp"',
    )]
    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'picture')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 500)]
    private ?string $picture = null;
    
    #[Assert\NotBlank(message: "Le prix de vente est obligatoire.")]
    #[Assert\Positive(message: "Le prix de vente doit être un nombre positif.")]
    #[Assert\Regex(
            pattern: "/^\d+(.\d{1,2})?$/",
            message: "Le prix de vente doit être un entier ou un nombre décimal avec au plus deux décimales."
    )]
    #[Assert\Range(
            min: 0.1,
            max: 9999999,
            notInRangeMessage: 'Le prix de vente doit être compris entre {{ min }} euros {{ max }} euros.',
    )]
    #[ORM\Column(type: Types::DECIMAL, precision: 6, scale: 2)]
    private ?string $price = null;
    
    #[Assert\Length(
        max: 255,
        maxMessage: 'La descriptio, ne doit pas depasser {{ limit }} caractères',
    )]
    #[Assert\NotBlank(message: 'La description est obligatoire')]
    #[ORM\Column(length: 500)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $isPublished = false;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $publishedAt = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $Category = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            
        }
    }


    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setPublished(bool $isPublished): static
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeImmutable $publishedAt): static
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): static
    {
        $this->Category = $Category;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/Admin/Product/ProductController.php
<?php

namespace App\Controller\Admin\Product;



use DateTimeImmutable;
use App\Entity\Product;
use App\Form\ProductFormType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin')]
class ProductController extends AbstractController
{
    #[Route('/product', name: 'app_product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('pages/admin/product/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    #[Route('/create', name: 'app_product_create', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductFormType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($product);
            $em->flush();

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pages/admin/product/new.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/product/{id<\d+>}/publish', name: 'admin_product_publish', methods: ['POST'])]
    public function publish(Product $product, Request $request, EntityManagerInterface $em): Response
    {
        //permet de vérifier si le jeton est valide
        if($this->isCsrfTokenValid("publish_product_{$product->getId()}", $request->request->get('_csrf_token') ))
        {
        // Si l'article n'a pas encore été publié
        if ( false === $product->isPublished() ) 
        {
            // Publier l'article
                $product->setPublished(true);
            // Mettre à jour sa date de publication
                $product->setPublishedAt(new DateTimeImmutable());
                          
            // Demander au manager des entités de préparer la requête de modification
                $em->persist($product);
            // Générer le message flash expliquant que l'article a été publié
                $this->addFlash("success", "L'article {$product->getName()} a été publié avec succès");

                
        }
        else
        {
            // Retirer l'article de la liste des publications
                $product->setPublished(false);
            // Mettre à nul la date de publication
                $product->setPublishedAt(null);
                            
            // Demander au manager des entités de préparer la requête de modification
                $em->persist($product);
            // Générer le message expliquant de l'article a été retiré de la liste des publications
                $this->addFlash("success", "L'article {$product->getName()} a été retiré des publications");
        }
        // Demander au manager des entités d'exécuter la requête préparée
        $em->flush();
        // Effectuer une redirection vers la page listant les articles 
            // Puis, arrêter l'exécution du script
    }       
        return $this->redirectToRoute('app_product_index');
    }

    #[Route('/product/{id<\d+>}/{slug}/show', name: 'app_product_show', methods: ['GET'])]
    public function show(Product $product): Response
    {
        return $this->render('pages/admin/product/show.html.twig', [
            'product' => $product,
        ]);
    }

    #[Route('/product/{id<\d+>}/edit', name: 'app_product_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Product $product, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(ProductFormType::class, $product);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em->persist($product);
            $em->flush();

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pages/admin/product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/product/{id}', name: 'app_product_delete', methods: ['POST'])]
    public function delete(Request $request, Product $product, EntityManagerInterface $em): Response
    {
        if ($this->isCsrfTokenValid("delete_product_{$product->getId()}", $request->request->get('_csrf_token') )) {
            $em->remove($product);
            $em->flush();
            $this->addFlash("success", "L'article {$product->getName()} a été supprimé avec succès");
        }

        return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pages/admin/product/edit.html.twig
{% extends 'themes/base_admin.html.twig' %}

{% block title %}Modifier {{product.name}}{% endblock %}

{% block description %}Modifier ce produit{% endblock %}

{% block keywords %}Admin, Modifier, produit{% endblock %} 
 
{% block main %}
 <h1 class="text-center my-3 display-5">Modifier ce produit<hr></h1>
    {% include 'components/_alert.html.twig' %}
    

    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-9 mx-auto">
                {{form_start(form)}}
                    <div class="mb-3">
                        <label for="admin_post_form_name">Name</label>
                        {{form_widget(form.name, {'attr':{'class':'form-control', 'autofocus':'autofocus'}})}}
                        <div class="text-danger">{{form_errors(form.name)}}</div>
                    </div>
                    <div class="mb-3">
                        <label for="admin_post_form_category">Catégorie</label>
                        {{form_widget(form.Category, {'attr':{'class':'form-control'}})}}
                        <div class="text-danger">{{form_errors(form.Category)}}</div>
                    </div>
                    <div class="mb-3">
                        <label for="admin_post_form_imageFile_image">Image</label>
                        {{form_widget(form.imageFile, {'attr':{'class':'form-control'}})}}
                        <div class="text-danger">{{form_errors(form.imageFile)}}</div>
                    </div>
                    <div class="mb-3">
                        <label for="admin_post_form_price">Prix de vente</label>
                        {{form_widget(form.price, {'attr':{'class':'form-control'}})}}
                        <div class="text-danger">{{form_errors(form.price)}}</div>
                    </div>
                    <div class="mb-3">
                        <label for="admin_post_form_content">Description</label>
                        {{ form_widget(form.description, {"id":"editor", "attr":{"class":"form-control", "rows":10}}) }}
                        <div class="text-danger">{{form_errors(form.description)}}</div>
                    </div>
                    <div class="mb-3 d-flex justify-content-between">
                        <input formnovalidate type="submit" class="btn btn-secondary shadow" value="Modifier">
                        <a href="{{path('app_product_index')}}" class="btn btn-secondary"> Retour</a>
                    </div>
                {{form_end(form)}}
            </div>
        </div>
    </div>
    {% block ckEditor %}
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>
    {% endblock %}
{% endblock %}

templates/pages/admin/product/index.html.twig
{% extends 'themes/base_admin.html.twig' %}

{% block title %}Liste des produits{% endblock %}

{% block description %}Liste des produits{% endblock %}

{% block keywords %}Admin, liste, produits{% endblock %}

{% block jQuery %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block DataTables %}
    <link href="https://cdn.datatables.net/v/bs5/dt-2.0.7/datatables.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/v/bs5/dt-2.0.7/datatables.min.js"></script>
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable({
                language: { 
                    url: 'https://cdn.datatables.net/plug-ins/2.0.7/i18n/fr-FR.json'
                },
            })
        } );
    </script>
{% endblock %}

{% block main %}
    <h1 class="my-3 text-center">Liste des produits</h1>
    {% include 'components/_alert.html.twig' %}
    <div class="d-flex justify-content-end align-items-center my-3">
        <a href="{{path('app_product_create')}}" class="btn btn-secondary shadow"><i class="fa-solid fa-plus"></i> Nouveau produit</a>
    </div>
    <div class="table-responsive mx-auto">
        <table  id="myTable" class="table table-hover text-center table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Slug</th>
                    <th>Catégorie</th>
                    <th>Image</th>
                    <th>Prix de vente</th>
                    <th>Description</th>
                    <th>Est publié?</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.slug }}</td>
                    <td>{{ product.category.name}}</td>
                    <td><img  src="{{vich_uploader_asset(product, 'imageFile') | imagine_filter('admin') }}" alt="{{product.name}}"></td>
                    <td>{{ product.price }} €</td>
                    <td>{{ product.description }}</td>
                    <td>{% if product.isPublished %}
                        <div>
                            <p>Oui publié le : </p>
                            {{product.publishedAt | format_datetime()}}
                        </div>
                        {% else %}
                            <p>Non</p>
                        {% endif %}</td>
                
                    <td>
                        <div class="d-flex flex-column justify-content-around h-100">
                            <form action="{{path('admin_product_publish', {'id': product.id})}}" method="post" class="mb-2">
                                <input type="hidden" name="_csrf_token" value="{{csrf_token('publish_product_'~product.id)}}">
                                <div class="form-check form-switch d-flex flex-column align-items-center">
                                    <input onclick="return confirm('Confirmer cette action?')" onchange="this.form.submit()" class="form-check-input" type="checkbox" role="switch" {{product.isPublished ?'checked' :''}}>
                                </div>
                            </form>
                            <a href="{{path('app_product_show', {'id': product.id ,'slug' : product.slug })}}"><i class="fa-solid fa-eye"></i></a>
                            <a href="{{path('app_product_edit', {'id' : product.id})}}"><i class="fa-solid fa-pen mt-4"></i></a>
                            <form action="{{path('app_product_delete', {'id':product.id})}}" method="post">
                                <input type="hidden" name="_csrf_token" value="{{csrf_token('delete_product_'~product.id)}}"> 
                                <button onclick="return confirm('Confirmer cette action?')" class="border-0 bg-white" type="submit"><i style='color:red' class="fa-solid fa-trash mt-4"></i></button> 
                            </form>
                            </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    
{% endblock %}

templates/pages/admin/product/new.html.twig
{% extends 'themes/base_admin.html.twig' %}

{% block title %}Créer un produit{% endblock %}

{% block description %}Créer un produit{% endblock %}

{% block keywords %}Admin, créer, produit{% endblock %} 
 
{% block main %}
 <h1 class="text-center my-3 display-5">Nouvel article<hr></h1>
    {% include 'components/_alert.html.twig' %}
    

    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-9 mx-auto">
                {{form_start(form)}}
                    <div class="mb-3">
                        <label for="admin_post_form_name">Name</label>
                        {{form_widget(form.name, {'attr':{'class':'form-control', 'autofocus':'autofocus'}})}}
                        <div class="text-danger">{{form_errors(form.name)}}</div>
                    </div>
                    <div class="mb-3">
                        <label for="admin_post_form_category">Catégorie</label>
                        {{form_widget(form.Category, {'attr':{'class':'form-control'}})}}
                        <div class="text-danger">{{form_errors(form.Category)}}</div>
                    </div>
                    <div class="mb-3">
                        <label for="admin_post_form_imageFile_image">Image</label>
                        {{form_widget(form.imageFile, {'attr':{'class':'form-control'}})}}
                        <div class="text-danger">{{form_errors(form.imageFile)}}</div>
                    </div>
                    <div class="mb-3">
                        <label for="admin_post_form_price">Prix de vente</label>
                        {{form_widget(form.price, {'attr':{'class':'form-control'}})}}
                        <div class="text-danger">{{form_errors(form.price)}}</div>
                    </div>
                    <div class="mb-3">
                        <label for="admin_post_form_content">Description</label>
                        {{ form_widget(form.description, {"id":"editor", "attr":{"class":"form-control", "rows":10}}) }}
                        <div class="text-danger">{{form_errors(form.description)}}</div>
                    </div>
                    <div class="mb-3">
                        <input formnovalidate type="submit" class="btn btn-secondary shadow" value="Ajouter">
                    </div>
                {{form_end(form)}}
            </div>
        </div>
    </div>
    {% block ckEditor %}
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .catch( error => {
                console.error( error );
            } );
    </script>
    {% endblock %}
{% endblock %}

templates/pages/admin/product/show.html.twig
{% extends 'themes/base_admin.html.twig' %}


{% block title %}{{product.name}}{% endblock %}

{% block description %}Détail du produit{% endblock %}

{% block keywords %}Admin, lire, produit{% endblock %}

{% block main %}
    <h1 class="text-center my-3 display-5"> {{product.name}}</h1>
    {% include 'components/_alert.html.twig' %}
        <div class="d-flex align-items-end my-2 flex-column">
            <div>
            {{product.category.name}}
            </div>
            <div>
            
            {% if product.isPublished %}
                <small><em>| publié le : {{product.publishedAt | format_date()}}</em></small>
            {% endif %}
            </div>
        </div>
    <div class="container-fluid">
        <div class="row img-fluid">
        {% if product.picture %}
            <img class="float" src="{{vich_uploader_asset(product, 'imageFile')}} " alt="{{product.name}}">
        {% endif %}
        </div>
        <div class="container-fluid">
            <p class="fw-bold mt-4">Description du produit <p>
            <p class=" mx-auto w-50 ">{{product.description | raw}}</p>
        </div>
    <a href="{{ path('app_product_index') }}" class="btn btn-secondary justify-content-end">retour</a>
    </div>
{% endblock %}


   